// Prisma SQLite does not support enums natively, so we enforce them here.

export enum Role {
  ADMINISTRATOR = 'ADMINISTRATOR',
  PROCUREMENT_OFFICER = 'PROCUREMENT_OFFICER',
  REVIEWER = 'REVIEWER',
  VIEWER = 'VIEWER',
}

export enum SpecificationType {
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  BOOLEAN = 'BOOLEAN',
  SELECT = 'SELECT',
}

export enum ComparisonType {
  MINIMUM = 'MINIMUM',
  MAXIMUM = 'MAXIMUM',
  EXACT = 'EXACT',
  ALLOWED_VALUE = 'ALLOWED_VALUE',
  TEXT_MATCH = 'TEXT_MATCH',
}

export enum ProcurementStatus {
  DRAFT = 'DRAFT',
  MARKET_RESEARCH = 'MARKET_RESEARCH',
  ANALYSIS = 'ANALYSIS',
  READY_FOR_PROCUREMENT = 'READY_FOR_PROCUREMENT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum QualificationStatus {
  QUALIFIED = 'QUALIFIED',
  NOT_QUALIFIED = 'NOT_QUALIFIED',
  INCOMPLETE = 'INCOMPLETE',
}

export enum CalculationMethod {
  MEDIAN_QUALIFIED_PRICES = 'MEDIAN_QUALIFIED_PRICES',
  LOWEST_QUALIFIED_PRICE = 'LOWEST_QUALIFIED_PRICE',
  AVERAGE_QUALIFIED_PRICES = 'AVERAGE_QUALIFIED_PRICES',
  SINGLE_QUALIFIED_PRICE = 'SINGLE_QUALIFIED_PRICE',
}
